version: 2.1

owner: "m-shoul"

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: ~/Messiah-Marketplace

jobs:
  eas_build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Login to Expo
          command: npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - run:
          name: Trigger build
          command: npx eas-cli build --platform android --non-interactive


workflows:
  build_app:
    jobs:
      - eas_build:
          filters:
            branches:
              only: main